#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Wheat Spike Trait Extraction Pipeline
======================================

A complete pipeline for extracting morphological, texture, color, and density
traits from wheat spike segmentation masks (e.g., generated by SAM) and their
corresponding original images.

This module provides:
  1. Single-image trait extraction: extract_all_wheat_traits(mask, image)
  2. Batch extraction across folders: batch_extract_all_traits(...)
  3. Mask quality filtering: enhanced_filter_flow(df, args)

Extracted trait categories (50+ features):
  - Shape: aspect_ratio (PCA + ellipse combined), area
  - Compactness: convex_hull_compactness, ellipse_compactness
  - Color: RGB/LAB/HSV statistics, hull color ratios (red/amber/white)
  - Texture: GLCM (contrast, homogeneity, dissimilarity, correlation, energy, ASM, entropy),
             LBP (multi-scale, rotation-invariant uniform)
  - Density: Voronoi density, spikelet count (peak detection), spikelet density (FFT)
  - Quality: composite quality score for mask filtering

Requirements:
  numpy, pandas, opencv-python (cv2), scipy, scikit-image, scikit-learn, shapely, tqdm

Usage:
  # Single image
  python trait_extraction_submission.py --single-mask mask.png --single-image image.png

  # Batch processing
  python trait_extraction_submission.py --mask-folder masks/ --image-folder images/ --output-csv traits.csv

  # As a library
  from trait_extraction_submission import extract_all_wheat_traits, batch_extract_all_traits

License: Apache License 2.0
"""

import os
import re
import gc
import time
import argparse
import traceback
from datetime import datetime

import numpy as np
import pandas as pd
import cv2
from tqdm import tqdm

from scipy.signal import find_peaks, savgol_filter
from scipy.fft import fft
from scipy.spatial import Voronoi
from scipy import stats

from skimage.feature import graycomatrix, graycoprops, local_binary_pattern, peak_local_max
from skimage.filters import threshold_otsu


# =============================================================================
# Utility Functions
# =============================================================================

def optimize_image_size(image, mask, max_size=1500):
    """Downsample large images to reduce memory usage.

    Args:
        image: Original image (H, W, C) or (H, W).
        mask: Corresponding mask image.
        max_size: Maximum dimension (width or height) before downsampling.

    Returns:
        (optimized_image, optimized_mask, scale_factor)
    """
    if image is None or mask is None:
        return image, mask, 1.0

    height, width = image.shape[:2]
    max_dim = max(height, width)

    if max_dim > max_size:
        scale_factor = max_size / max_dim
        new_width = int(width * scale_factor)
        new_height = int(height * scale_factor)

        optimized_image = cv2.resize(image, (new_width, new_height),
                                     interpolation=cv2.INTER_AREA)
        optimized_mask = cv2.resize(mask, (new_width, new_height),
                                    interpolation=cv2.INTER_NEAREST)
        return optimized_image, optimized_mask, scale_factor

    return image, mask, 1.0


# =============================================================================
# Mask Preprocessing
# =============================================================================

def smooth_wheat_mask(mask, quality_check=True):
    """Smooth a wheat spike mask by keeping the largest connected component
    and optionally applying morphological operations.

    Args:
        mask: Binary mask image (uint8, 0/255).
        quality_check: If True, only apply morphological smoothing when
                       contour complexity exceeds a threshold.

    Returns:
        Smoothed binary mask (uint8, 0/255).
    """
    result = mask.copy()

    # Keep only the largest connected component
    mask_bool = (result > 0)
    num_labels, labels, stats_arr, centroids = cv2.connectedComponentsWithStats(
        mask_bool.astype(np.uint8), connectivity=8)

    if num_labels > 1:
        max_label = 1
        max_area = stats_arr[1, cv2.CC_STAT_AREA]
        for j in range(2, num_labels):
            area = stats_arr[j, cv2.CC_STAT_AREA]
            if area > max_area:
                max_area = area
                max_label = j
        result = (labels == max_label).astype(np.uint8) * 255
    else:
        if num_labels <= 1:
            return np.zeros_like(mask_bool, dtype=np.uint8)

    contours, _ = cv2.findContours(result, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    if len(contours) == 0:
        return result

    main_contour = max(contours, key=cv2.contourArea)
    perimeter = cv2.arcLength(main_contour, True)
    area = cv2.contourArea(main_contour)
    complexity = perimeter**2 / (4 * np.pi * area) if area > 0 else float('inf')

    if not quality_check or complexity > 1.5:
        kernel_open = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
        result = cv2.morphologyEx(result, cv2.MORPH_OPEN, kernel_open)

        kernel_close = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
        result = cv2.morphologyEx(result, cv2.MORPH_CLOSE, kernel_close)

        result = cv2.GaussianBlur(result, (5, 5), 0)
        _, result = cv2.threshold(result, 127, 255, cv2.THRESH_BINARY)

    return result


# =============================================================================
# Shape Features: Aspect Ratio
# =============================================================================

def aspect_ratio_pca(mask):
    """Compute aspect ratio using PCA on mask pixel coordinates.

    Args:
        mask: Binary mask image.

    Returns:
        (aspect_ratio, axes_info_dict) or None if too few points.
        axes_info_dict contains: mean, eigenvectors, axis_length,
        main_axis (endpoints), minor_axis (endpoints).
    """
    points = np.where(mask > 0)
    points = np.column_stack((points[1], points[0]))  # (x, y) order

    if len(points) < 3:
        return None

    mean = np.mean(points, axis=0)
    cov = np.cov(points.T)
    eigenvalues, eigenvectors = np.linalg.eig(cov)

    sort_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sort_indices]
    eigenvectors = eigenvectors[:, sort_indices]

    axis_length = 4 * np.sqrt(eigenvalues)  # 4-sigma covers ~95% of points

    aspect_ratio = axis_length[0] / axis_length[1] if axis_length[1] > 0 else float('inf')

    main_axis_endpoint1 = mean + eigenvectors[:, 0] * axis_length[0] / 2
    main_axis_endpoint2 = mean - eigenvectors[:, 0] * axis_length[0] / 2
    minor_axis_endpoint1 = mean + eigenvectors[:, 1] * axis_length[1] / 2
    minor_axis_endpoint2 = mean - eigenvectors[:, 1] * axis_length[1] / 2

    axes_info = {
        'mean': mean,
        'eigenvectors': eigenvectors,
        'axis_length': axis_length,
        'main_axis': (main_axis_endpoint1, main_axis_endpoint2),
        'minor_axis': (minor_axis_endpoint1, minor_axis_endpoint2)
    }

    return aspect_ratio, axes_info


def aspect_ratio_ellipse(mask):
    """Compute aspect ratio using minimum enclosing ellipse fit.

    Args:
        mask: Binary mask image.

    Returns:
        (aspect_ratio, info_dict) or None if contour too small.
        info_dict contains: ellipse parameters, IoU with mask.
    """
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    if len(contours) == 0:
        return None

    contour = max(contours, key=cv2.contourArea)
    if len(contour) < 5:
        return None

    ellipse = cv2.fitEllipse(contour)
    (x, y), (width, height), angle = ellipse

    length = max(width, height)
    width = min(width, height)
    aspect_ratio = length / width if width > 0 else float('inf')

    # Evaluate fit quality via IoU
    ellipse_mask = np.zeros_like(mask)
    cv2.ellipse(ellipse_mask, ellipse, 255, -1)
    intersection = np.logical_and(mask > 0, ellipse_mask > 0).sum()
    union = np.logical_or(mask > 0, ellipse_mask > 0).sum()
    iou = intersection / union if union > 0 else 0

    return aspect_ratio, {'ellipse': ellipse, 'iou': iou}


def aspect_ratio_combined(mask, weights=None):
    """Compute aspect ratio by combining PCA and ellipse methods with
    adaptive weighting based on ellipse fit quality.

    Args:
        mask: Binary mask image.
        weights: Optional dict with 'pca' and 'ellipse' weights.

    Returns:
        (combined_ratio, info_dict) or None.
    """
    if weights is None:
        weights = {'pca': 0.5, 'ellipse': 0.5}

    results = {}

    pca_result = aspect_ratio_pca(mask)
    if pca_result is not None:
        results['pca'] = pca_result[0]

    ellipse_result = aspect_ratio_ellipse(mask)
    if ellipse_result is not None:
        ellipse_quality = ellipse_result[1]['iou']
        results['ellipse'] = ellipse_result[0]
        if ellipse_quality > 0.85:
            weights['ellipse'] = min(0.7, weights['ellipse'] * 1.5)
            weights['pca'] = 1.0 - weights['ellipse']
        elif ellipse_quality < 0.4:
            weights['ellipse'] = max(0.3, weights['ellipse'] * 0.8)
            weights['pca'] = 1.0 - weights['ellipse']

    weighted_sum = 0
    total_weight = 0
    for method, value in results.items():
        if method in weights:
            weighted_sum += value * weights[method]
            total_weight += weights[method]

    if total_weight > 0:
        combined_ratio = weighted_sum / total_weight
    else:
        return None

    return combined_ratio, {
        'individual_results': results,
        'weights': weights
    }


# =============================================================================
# Shape Features: Compactness
# =============================================================================

def calculate_convex_hull_compactness(mask):
    """Compute convex hull compactness (mask_area / hull_area).

    Args:
        mask: Binary mask image.

    Returns:
        (compactness, info_dict) or None.
    """
    contours, _ = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    largest_contour = max(contours, key=cv2.contourArea)
    original_area = cv2.contourArea(largest_contour)
    hull = cv2.convexHull(largest_contour)
    hull_area = cv2.contourArea(hull)

    compactness = original_area / hull_area if hull_area > 0 else 0

    return compactness, {
        'original_area': original_area,
        'hull_area': hull_area,
        'hull': hull
    }


def calculate_ellipse_compactness(mask):
    """Compute ellipse compactness (mask_area / ellipse_area).

    Args:
        mask: Binary mask image.

    Returns:
        (compactness, info_dict) or None.
    """
    contours, _ = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    largest_contour = max(contours, key=cv2.contourArea)
    original_area = cv2.contourArea(largest_contour)

    if len(largest_contour) >= 5:
        ellipse = cv2.fitEllipse(largest_contour)
        center, axes, angle = ellipse
        a, b = axes[0] / 2, axes[1] / 2
        ellipse_area = np.pi * a * b

        compactness = original_area / ellipse_area if ellipse_area > 0 else 0

        return compactness, {
            'original_area': original_area,
            'ellipse_area': ellipse_area,
            'ellipse': ellipse
        }

    return None


# =============================================================================
# Texture Features: GLCM (Gray-Level Co-occurrence Matrix)
# =============================================================================

def extract_glcm_features_advanced(mask, original_image):
    """Extract GLCM texture features along the PCA-aligned main axis.

    Computes 7 features at multiple distances [1, 3, 5]:
    contrast, homogeneity, dissimilarity, correlation, energy, ASM, entropy.

    Args:
        mask: Binary mask image.
        original_image: Original color or grayscale image.

    Returns:
        Dict of GLCM features, or None on failure.
    """
    if len(original_image.shape) == 3:
        gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
    else:
        gray_image = original_image.copy()

    mask_bool = mask > 0
    roi = np.zeros_like(gray_image)
    roi[mask_bool] = gray_image[mask_bool]

    if np.sum(mask_bool) == 0:
        return None

    # Determine PCA-aligned angle for GLCM
    pca_result = aspect_ratio_pca(mask)
    if pca_result is None:
        angles = [0]
    else:
        _, axes_info = pca_result
        eigenvectors = axes_info['eigenvectors']
        main_axis_vector = eigenvectors[:, 0]
        angle_rad = np.arctan2(main_axis_vector[1], main_axis_vector[0])
        angle_deg = np.degrees(angle_rad)

        std_angles = [0, 45, 90, 135]
        main_angle = angle_deg % 180
        closest_angle_idx = np.argmin(
            [abs((main_angle - ang) % 180) for ang in std_angles])
        main_glcm_angle = std_angles[closest_angle_idx]
        angles = [np.radians(main_glcm_angle)]

    rows, cols = np.where(mask_bool)
    if len(rows) == 0 or len(cols) == 0:
        return None

    min_row, max_row = np.min(rows), np.max(rows)
    min_col, max_col = np.min(cols), np.max(cols)

    roi_cropped = roi[min_row:max_row + 1, min_col:max_col + 1]
    mask_cropped = mask_bool[min_row:max_row + 1, min_col:max_col + 1]

    if roi_cropped.max() > 0:
        roi_normalized = ((roi_cropped / roi_cropped.max()) * 255).astype(np.uint8)
    else:
        return None

    distances = [1, 3, 5]
    levels = 256
    symmetric = True
    normed = True

    features = {}

    try:
        roi_masked = roi_normalized.copy()
        roi_masked[~mask_cropped] = 0

        glcm = graycomatrix(roi_masked, distances=distances, angles=angles,
                            levels=levels, symmetric=symmetric, normed=normed)

        properties = ['contrast', 'homogeneity', 'dissimilarity',
                      'correlation', 'energy']
        for prop in properties:
            try:
                value = graycoprops(glcm, prop).mean()
                features[f'glcm_{prop}'] = value
            except Exception:
                features[f'glcm_{prop}'] = 0

        # ASM = energy^2
        try:
            features['glcm_asm'] = features.get('glcm_energy', 0) ** 2
        except Exception:
            features['glcm_asm'] = 0

        # Entropy (not provided by graycoprops)
        try:
            entropy_val = 0
            for i in range(glcm.shape[0]):
                for j in range(glcm.shape[1]):
                    for a in range(glcm.shape[2]):
                        for d in range(glcm.shape[3]):
                            if glcm[i, j, a, d] > 0:
                                entropy_val -= glcm[i, j, a, d] * np.log2(glcm[i, j, a, d])
            features['glcm_entropy'] = entropy_val / (glcm.shape[2] * glcm.shape[3])
        except Exception:
            features['glcm_entropy'] = 0

        return features
    except Exception as e:
        print(f"GLCM computation error: {str(e)}")
        return None


# =============================================================================
# Texture Features: LBP (Local Binary Pattern)
# =============================================================================

def extract_multiscale_lbp_features(mask, original_image):
    """Extract multi-scale LBP texture features.

    Uses uniform and rotation-invariant LBP at radii [1, 2] with [8, 16] neighbors.
    Adapts parameters based on ROI size.

    Args:
        mask: Binary mask image.
        original_image: Original color or grayscale image.

    Returns:
        Dict of LBP features.
    """
    default_features = {
        'lbp_mean': 0.0, 'lbp_std': 0.0, 'lbp_energy': 0.0,
        'lbp_r1_mean': 0.0, 'lbp_r1_std': 0.0, 'lbp_r1_energy': 0.0,
        'lbp_r2_mean': 0.0, 'lbp_r2_std': 0.0, 'lbp_r2_energy': 0.0,
        'lbp_riu2_mean': 0.0, 'lbp_riu2_std': 0.0, 'lbp_riu2_energy': 0.0
    }

    if mask is None or original_image is None:
        return default_features

    if len(original_image.shape) == 3:
        gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
    else:
        gray_image = original_image.copy()

    mask_bool = mask > 0
    roi = np.zeros_like(gray_image)
    roi[mask_bool] = gray_image[mask_bool]

    if np.sum(mask_bool) == 0:
        return default_features

    features = default_features.copy()

    try:
        rows, cols = np.where(mask_bool)
        if len(rows) == 0 or len(cols) == 0:
            return default_features

        height = np.max(rows) - np.min(rows) + 1
        width = np.max(cols) - np.min(cols) + 1

        min_row, max_row = np.min(rows), np.max(rows)
        min_col, max_col = np.min(cols), np.max(cols)
        roi_cropped = roi[min_row:max_row + 1, min_col:max_col + 1]
        mask_cropped = mask_bool[min_row:max_row + 1, min_col:max_col + 1]

        roi_blurred = cv2.GaussianBlur(roi_cropped, (3, 3), 0)

        # Rotation-invariant uniform LBP (P=8, R=1)
        try:
            radius = 1
            n_points = 8
            try:
                lbp_riu2 = local_binary_pattern(roi_blurred, n_points, radius, method='ror')
            except ValueError:
                lbp_riu2 = local_binary_pattern(roi_blurred, n_points, radius, method='uniform')

            lbp_riu2_values = lbp_riu2[mask_cropped]
            if len(lbp_riu2_values) > 0:
                features['lbp_riu2_mean'] = np.mean(lbp_riu2_values)
                features['lbp_riu2_std'] = np.std(lbp_riu2_values)
                features['lbp_riu2_energy'] = np.sum(lbp_riu2_values**2) / len(lbp_riu2_values)
        except Exception:
            pass

        # Multi-scale LBP adapted to ROI size
        if min(height, width) < 30:
            # Very small target: single scale
            radius, n_points = 1, 8
            lbp = local_binary_pattern(roi_blurred, n_points, radius, method='uniform')
            lbp_values = lbp[mask_cropped]

            if len(lbp_values) > 0:
                features['lbp_mean'] = np.mean(lbp_values)
                features['lbp_std'] = np.std(lbp_values)
                features['lbp_energy'] = np.sum(lbp_values**2) / len(lbp_values)
                features['lbp_r1_mean'] = features['lbp_mean']
                features['lbp_r1_std'] = features['lbp_std']
                features['lbp_r1_energy'] = features['lbp_energy']
        else:
            for radius, n_points in [(1, 8), (2, 16)]:
                lbp = local_binary_pattern(roi_blurred, n_points, radius, method='uniform')
                lbp_values = lbp[mask_cropped]

                if len(lbp_values) > 0:
                    prefix = f'lbp_r{radius}'
                    features[f'{prefix}_mean'] = np.mean(lbp_values)
                    features[f'{prefix}_std'] = np.std(lbp_values)
                    features[f'{prefix}_energy'] = np.sum(lbp_values**2) / len(lbp_values)

                    if radius == 1:
                        features['lbp_mean'] = features[f'{prefix}_mean']
                        features['lbp_std'] = features[f'{prefix}_std']
                        features['lbp_energy'] = features[f'{prefix}_energy']

        return features

    except Exception as e:
        print(f"LBP feature extraction error: {str(e)}")
        return default_features


# =============================================================================
# Density Features: Voronoi
# =============================================================================

def calculate_voronoi_density(mask, original_image, min_distance=5, threshold_abs=0.02):
    """Compute Voronoi tessellation-based spatial density analysis.

    Detects local intensity peaks within the mask ROI, builds a Voronoi
    diagram, and computes area statistics.

    Args:
        mask: Binary mask image.
        original_image: Original color or grayscale image.
        min_distance: Minimum distance for peak detection.
        threshold_abs: Absolute threshold for peak detection.

    Returns:
        Dict with voronoi_mean_area, voronoi_std_area, voronoi_density,
        voronoi_points_count, voronoi_points_per_area.
    """
    default_features = {
        'voronoi_mean_area': 0.0, 'voronoi_std_area': 0.0,
        'voronoi_density': 0.0, 'voronoi_points_count': 0,
        'voronoi_points_per_area': 0.0
    }

    if mask is None or original_image is None:
        return default_features

    if len(original_image.shape) == 3:
        gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
    else:
        gray_image = original_image.copy()

    mask_bool = mask > 0
    roi = np.zeros_like(gray_image)
    roi[mask_bool] = gray_image[mask_bool]

    if np.sum(mask_bool) == 0:
        return default_features

    try:
        rows, cols = np.where(mask_bool)
        if len(rows) == 0 or len(cols) == 0:
            return default_features

        min_row, max_row = np.min(rows), np.max(rows)
        min_col, max_col = np.min(cols), np.max(cols)
        roi_cropped = roi[min_row:max_row + 1, min_col:max_col + 1]
        mask_cropped = mask_bool[min_row:max_row + 1, min_col:max_col + 1]

        roi_enhanced = cv2.equalizeHist(roi_cropped)
        roi_blurred = cv2.GaussianBlur(roi_enhanced, (3, 3), 0)

        height, width = roi_cropped.shape
        if min(height, width) < 30:
            adjusted_min_distance, adjusted_threshold = 3, 0.01
        elif min(height, width) < 60:
            adjusted_min_distance, adjusted_threshold = 4, 0.015
        else:
            adjusted_min_distance, adjusted_threshold = min_distance, threshold_abs

        coordinates = peak_local_max(roi_blurred,
                                     min_distance=adjusted_min_distance,
                                     threshold_abs=adjusted_threshold)

        if len(coordinates) < 3:
            coordinates = peak_local_max(roi_blurred,
                                         min_distance=2, threshold_abs=0.005)

        if len(coordinates) < 3:
            return default_features

        roi_area = np.sum(mask_cropped)
        vor = Voronoi(coordinates)

        areas = []
        for region_idx in vor.point_region:
            region = vor.regions[region_idx]
            if -1 not in region and len(region) > 0:
                polygon = [vor.vertices[i] for i in region]
                if len(polygon) >= 3:
                    area = 0
                    for i in range(len(polygon)):
                        j = (i + 1) % len(polygon)
                        area += polygon[i][0] * polygon[j][1]
                        area -= polygon[j][0] * polygon[i][1]
                    area = abs(area) / 2
                    areas.append(area)

        if len(areas) == 0:
            return default_features

        mean_area = np.mean(areas)
        std_area = np.std(areas)
        points_per_area = len(coordinates) / roi_area if roi_area > 0 else 0
        voronoi_density = 1.0 / mean_area if mean_area > 0 else 0

        features = default_features.copy()
        features.update({
            'voronoi_mean_area': mean_area,
            'voronoi_std_area': std_area,
            'voronoi_density': voronoi_density,
            'voronoi_points_count': len(coordinates),
            'voronoi_points_per_area': points_per_area
        })
        return features

    except Exception as e:
        print(f"Voronoi density error: {str(e)}")
        return default_features


# =============================================================================
# Density Features: Spikelet Counting
# =============================================================================

def estimate_spikelet_count_peaks(mask, original_image):
    """Estimate spikelet count by detecting peaks in the intensity profile
    along the PCA main axis.

    Args:
        mask: Binary mask image.
        original_image: Original color or grayscale image.

    Returns:
        Dict with spikelet_count, spikelet_density.
    """
    if len(original_image.shape) == 3:
        gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
    else:
        gray_image = original_image.copy()

    mask_bool = mask > 0
    roi = np.zeros_like(gray_image)
    roi[mask_bool] = gray_image[mask_bool]

    if np.sum(mask_bool) == 0:
        return {'spikelet_count': 0, 'spikelet_density': 0}

    try:
        coords = np.column_stack(np.where(mask_bool))
        if len(coords) < 2:
            return {'spikelet_count': 0, 'spikelet_density': 0}

        mean = np.mean(coords, axis=0)
        coords_centered = coords - mean
        cov = np.cov(coords_centered.T)
        eigenvalues, eigenvectors = np.linalg.eig(cov)

        idx = np.argmax(eigenvalues)
        main_axis = eigenvectors[:, idx]
        projected = np.dot(coords_centered, main_axis)

        sort_idx = np.argsort(projected)
        coords_sorted = coords[sort_idx]

        intensity_profile = []
        for coord in coords_sorted:
            x, y = coord
            if 0 <= x < roi.shape[0] and 0 <= y < roi.shape[1]:
                intensity_profile.append(roi[x, y])

        if not intensity_profile or len(intensity_profile) < 3:
            return {'spikelet_count': 0, 'spikelet_density': 0}

        intensity_profile = np.array(intensity_profile)
        window_length = min(5, len(intensity_profile) -
                            (1 if len(intensity_profile) % 2 == 0 else 0))
        if window_length >= 3:
            intensity_profile = savgol_filter(intensity_profile, window_length, 2)

        peaks, _ = find_peaks(intensity_profile, distance=5)
        spikelet_count = len(peaks)

        axis_length = np.max(projected) - np.min(projected)
        spikelet_density = spikelet_count / axis_length if axis_length > 0 else 0

        return {
            'spikelet_count': spikelet_count,
            'spikelet_density': spikelet_density
        }
    except Exception as e:
        print(f"Spikelet detection error: {str(e)}")
        return {'spikelet_count': 0, 'spikelet_density': 0}


def estimate_spikelet_density_frequency(mask, original_image):
    """Estimate spikelet density using FFT-based frequency analysis of the
    intensity profile along the PCA main axis.

    Args:
        mask: Binary mask image.
        original_image: Original color or grayscale image.

    Returns:
        Dict with dominant_frequency, estimated_spikelet_count, spikelet_density.
    """
    if len(original_image.shape) == 3:
        gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
    else:
        gray_image = original_image.copy()

    mask_bool = mask > 0
    roi = np.zeros_like(gray_image)
    roi[mask_bool] = gray_image[mask_bool]

    if np.sum(mask_bool) == 0:
        return {'dominant_frequency': 0, 'estimated_spikelet_count': 0, 'spikelet_density': 0}

    try:
        coords = np.column_stack(np.where(mask_bool))
        if len(coords) < 2:
            return {'dominant_frequency': 0, 'estimated_spikelet_count': 0, 'spikelet_density': 0}

        mean = np.mean(coords, axis=0)
        coords_centered = coords - mean
        cov = np.cov(coords_centered.T)
        eigenvalues, eigenvectors = np.linalg.eig(cov)

        idx = np.argmax(eigenvalues)
        main_axis = eigenvectors[:, idx]
        projected = np.dot(coords_centered, main_axis)

        sort_idx = np.argsort(projected)
        coords_sorted = coords[sort_idx]

        intensity_profile = []
        for coord in coords_sorted:
            x, y = coord
            if 0 <= x < roi.shape[0] and 0 <= y < roi.shape[1]:
                intensity_profile.append(roi[x, y])

        if len(intensity_profile) < 10:
            return {'dominant_frequency': 0, 'estimated_spikelet_count': 0, 'spikelet_density': 0}

        intensity_profile = np.array(intensity_profile)
        window_length = min(11, len(intensity_profile) -
                            (1 if len(intensity_profile) % 2 == 0 else 0))
        if window_length >= 3:
            intensity_profile = savgol_filter(intensity_profile, window_length, 2)

        fft_result = fft(intensity_profile)
        fft_magnitude = np.abs(fft_result)

        n = len(fft_magnitude) // 2
        if n <= 1:
            return {'dominant_frequency': 0, 'estimated_spikelet_count': 0, 'spikelet_density': 0}

        fft_magnitude = fft_magnitude[1:n]  # skip DC component

        peak_idx = np.argmax(fft_magnitude)
        dominant_frequency = (peak_idx + 1) / len(intensity_profile)
        estimated_spikelet_count = dominant_frequency * len(intensity_profile)

        axis_length = np.max(projected) - np.min(projected)
        spikelet_density = estimated_spikelet_count / axis_length if axis_length > 0 else 0

        return {
            'dominant_frequency': dominant_frequency,
            'estimated_spikelet_count': int(estimated_spikelet_count),
            'spikelet_density': spikelet_density
        }
    except Exception as e:
        print(f"FFT frequency analysis error: {str(e)}")
        return {'dominant_frequency': 0, 'estimated_spikelet_count': 0, 'spikelet_density': 0}


# =============================================================================
# Color Features
# =============================================================================

def extract_color_features(mask, original_image):
    """Extract color features from the mask region in multiple color spaces.

    Features include:
      - RGB channel means and stds
      - LAB channel means and stds (recommended for plant classification)
      - HSV key features (hue, saturation, value)
      - Hull color ratios: red, amber, white (key indicators for variety classification)

    Args:
        mask: Binary mask image (uint8, 0/255).
        original_image: Original color image (BGR).

    Returns:
        Dict of color features.
    """
    default_features = {
        'color_r_mean': 0.0, 'color_g_mean': 0.0, 'color_b_mean': 0.0,
        'color_r_std': 0.0, 'color_g_std': 0.0, 'color_b_std': 0.0,
        'color_lab_l_mean': 0.0, 'color_lab_a_mean': 0.0, 'color_lab_b_mean': 0.0,
        'color_lab_l_std': 0.0, 'color_lab_a_std': 0.0, 'color_lab_b_std': 0.0,
        'color_h_mean': 0.0, 'color_s_mean': 0.0, 'color_v_mean': 0.0,
        'color_h_std': 0.0,
        'color_red_ratio': 0.0, 'color_white_ratio': 0.0, 'color_amber_ratio': 0.0
    }

    if mask is None or original_image is None:
        return default_features

    mask_bool = mask > 0
    roi = cv2.bitwise_and(original_image, original_image, mask=mask)

    if np.sum(mask_bool) == 0:
        return default_features

    try:
        features = {}

        # RGB
        b, g, r = cv2.split(roi)
        r_values = r[mask_bool]
        g_values = g[mask_bool]
        b_values = b[mask_bool]

        features['color_r_mean'] = np.mean(r_values)
        features['color_g_mean'] = np.mean(g_values)
        features['color_b_mean'] = np.mean(b_values)
        features['color_r_std'] = np.std(r_values)
        features['color_g_std'] = np.std(g_values)
        features['color_b_std'] = np.std(b_values)

        # LAB
        lab = cv2.cvtColor(roi, cv2.COLOR_BGR2LAB)
        l, a, b_channel = cv2.split(lab)
        l_values = l[mask_bool]
        a_values = a[mask_bool]
        lab_b_values = b_channel[mask_bool]

        features['color_lab_l_mean'] = np.mean(l_values)
        features['color_lab_a_mean'] = np.mean(a_values)
        features['color_lab_b_mean'] = np.mean(lab_b_values)
        features['color_lab_l_std'] = np.std(l_values)
        features['color_lab_a_std'] = np.std(a_values)
        features['color_lab_b_std'] = np.std(lab_b_values)

        # HSV
        hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
        h, s, v = cv2.split(hsv)
        h_values = h[mask_bool]
        s_values = s[mask_bool]
        v_values = v[mask_bool]

        features['color_h_mean'] = np.mean(h_values)
        features['color_s_mean'] = np.mean(s_values)
        features['color_v_mean'] = np.mean(v_values)
        features['color_h_std'] = np.std(h_values)

        # Hull color ratios
        total_pixels = np.sum(mask_bool)

        # Red hull range
        red_mask1 = cv2.inRange(hsv, np.array([0, 30, 50]), np.array([20, 255, 255]))
        red_mask2 = cv2.inRange(hsv, np.array([160, 30, 50]), np.array([180, 255, 255]))
        red_mask = cv2.bitwise_or(red_mask1, red_mask2)
        features['color_red_ratio'] = np.sum(red_mask[mask_bool]) / (255.0 * total_pixels)

        # Amber/golden range
        amber_mask = cv2.inRange(hsv, np.array([20, 50, 150]), np.array([40, 255, 255]))
        features['color_amber_ratio'] = np.sum(amber_mask[mask_bool]) / (255.0 * total_pixels)

        # White/pale range
        white_mask = cv2.inRange(hsv, np.array([0, 0, 160]), np.array([60, 80, 255]))
        features['color_white_ratio'] = np.sum(white_mask[mask_bool]) / (255.0 * total_pixels)

        return features

    except Exception as e:
        print(f"Color feature extraction error: {str(e)}")
        return default_features


# =============================================================================
# Master Extraction Function
# =============================================================================

def extract_all_wheat_traits(mask, original_image):
    """Extract all wheat spike traits from a single mask-image pair.

    This is the main entry point for trait extraction. It orchestrates all
    sub-extraction functions and returns a unified dictionary of 50+ features.

    Args:
        mask: Binary mask image (uint8). Can be grayscale or color (will be
              converted to single channel). Values > 0 are treated as foreground.
        original_image: Original color image (BGR) or grayscale image.

    Returns:
        Dict with all extracted features, or None if inputs are invalid.

    Feature categories:
        Shape:    aspect_ratio, area_px
        Compact:  convex_compactness, ellipse_compactness
        Color:    color_r_mean, color_g_mean, color_b_mean, color_r_std, color_g_std,
                  color_b_std, color_lab_l_mean, color_lab_a_mean, color_lab_b_mean,
                  color_lab_l_std, color_lab_a_std, color_lab_b_std, color_h_mean,
                  color_s_mean, color_v_mean, color_h_std, color_red_ratio,
                  color_white_ratio, color_amber_ratio
        GLCM:     glcm_contrast, glcm_homogeneity, glcm_dissimilarity,
                  glcm_correlation, glcm_energy, glcm_asm, glcm_entropy
        LBP:      lbp_mean, lbp_std, lbp_energy, lbp_r1_mean, lbp_r1_std,
                  lbp_r1_energy, lbp_r2_mean, lbp_r2_std, lbp_r2_energy,
                  lbp_riu2_mean, lbp_riu2_std, lbp_riu2_energy
        Voronoi:  voronoi_mean_area, voronoi_std_area, voronoi_density,
                  voronoi_points_count, voronoi_points_per_area
        Spikelet: spikelet_count, spikelet_density, dominant_frequency,
                  estimated_spikelet_count
    """
    if mask is None or original_image is None:
        return None

    if isinstance(mask, np.ndarray) and mask.dtype != np.uint8:
        mask = mask.astype(np.uint8)

    if len(mask.shape) == 3:
        mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)

    _, mask_binary = cv2.threshold(mask, 1, 255, cv2.THRESH_BINARY)
    mask_smooth = smooth_wheat_mask(mask_binary)

    all_features = {}

    # 1. Aspect ratio (shape)
    ar_result = aspect_ratio_combined(mask_smooth)
    all_features['aspect_ratio'] = ar_result[0] if ar_result is not None else 0

    # 2. Compactness (shape regularity)
    convex_result = calculate_convex_hull_compactness(mask_smooth)
    all_features['convex_compactness'] = convex_result[0] if convex_result is not None else 0

    ellipse_result = calculate_ellipse_compactness(mask_smooth)
    all_features['ellipse_compactness'] = ellipse_result[0] if ellipse_result is not None else 0

    # 3. Color features
    color_features = extract_color_features(mask_smooth, original_image)
    if color_features is not None:
        all_features.update(color_features)

    # 4. GLCM texture features
    glcm_features = extract_glcm_features_advanced(mask_smooth, original_image)
    if glcm_features is not None:
        all_features.update(glcm_features)

    # 5. LBP texture features
    lbp_features = extract_multiscale_lbp_features(mask_smooth, original_image)
    if lbp_features is not None:
        all_features.update(lbp_features)

    # 6. Voronoi density features
    voronoi_features = calculate_voronoi_density(mask_smooth, original_image)
    if voronoi_features is not None:
        all_features.update(voronoi_features)

    # 7. Spikelet count (peak detection)
    spikelet_features = estimate_spikelet_count_peaks(mask_smooth, original_image)
    if spikelet_features is not None:
        all_features.update(spikelet_features)

    # 8. Spikelet density (FFT frequency analysis)
    freq_features = estimate_spikelet_density_frequency(mask_smooth, original_image)
    if freq_features is not None:
        all_features.update(freq_features)

    # 9. Area
    all_features['area_px'] = np.sum(mask_smooth > 0)

    return all_features


# =============================================================================
# Batch Processing
# =============================================================================

def batch_extract_all_traits(mask_folder, original_image_folder, output_csv=None,
                             start_index=0, sample_limit=None, args=None):
    """Batch extract traits from all mask-image pairs in the given folders.

    Mask filenames are expected to follow the pattern: <original_name>_mask_<N>.png
    The corresponding original image is looked up as <original_name>.<ext>.

    Args:
        mask_folder: Path to folder containing mask images.
        original_image_folder: Path to folder containing original images.
        output_csv: Output CSV path. If None, results are not saved to disk.
        start_index: Index of first mask file to process.
        sample_limit: Maximum number of masks to process (None = all).
        args: Optional namespace with attributes:
              enable_memory_optimization (bool), max_image_size (int),
              batch_save_interval (int).

    Returns:
        pd.DataFrame with extracted traits, or None on failure.
    """
    if not os.path.exists(mask_folder):
        print(f"Error: Mask folder does not exist: {mask_folder}")
        return None

    if not os.path.exists(original_image_folder):
        print(f"Error: Image folder does not exist: {original_image_folder}")
        return None

    mask_files = sorted([f for f in os.listdir(mask_folder)
                         if f.endswith(('.png', '.jpg', '.jpeg', '.tif'))])

    print(f"Found {len(mask_files)} mask files")

    if start_index > 0 and start_index < len(mask_files):
        mask_files = mask_files[start_index:]

    if sample_limit is not None and sample_limit > 0:
        mask_files = mask_files[:sample_limit]

    if not mask_files:
        print("Error: No mask files to process")
        return None

    results = []
    failed_masks = []
    processed_originals = set()
    start_time = time.time()
    save_interval = getattr(args, 'batch_save_interval', 50) if args else 50
    enable_mem_opt = getattr(args, 'enable_memory_optimization', False) if args else False
    max_img_size = getattr(args, 'max_image_size', 1500) if args else 1500

    try:
        for i, mask_file in enumerate(tqdm(mask_files, desc="Extracting traits")):
            try:
                match = re.search(r'(.+)_mask_\d+\.\w+$', mask_file)
                if not match:
                    print(f"  Warning: Cannot parse original image name from {mask_file}")
                    failed_masks.append(mask_file)
                    continue

                original_basename = match.group(1)

                original_filename = None
                for ext in ['.jpg', '.jpeg', '.png', '.tif', '.bmp']:
                    temp_path = os.path.join(original_image_folder,
                                             original_basename + ext)
                    if os.path.exists(temp_path):
                        original_filename = original_basename + ext
                        break

                if original_filename is None:
                    print(f"  Warning: No matching original image for {mask_file}")
                    failed_masks.append(mask_file)
                    continue

                processed_originals.add(original_filename)

                mask_path = os.path.join(mask_folder, mask_file)
                original_path = os.path.join(original_image_folder, original_filename)

                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                original_image = cv2.imread(original_path)

                if mask is None:
                    print(f"  Warning: Cannot read mask {mask_file}")
                    failed_masks.append(mask_file)
                    continue

                if original_image is None:
                    print(f"  Warning: Cannot read image {original_filename}")
                    failed_masks.append(mask_file)
                    continue

                if mask.shape[:2] != original_image.shape[:2]:
                    mask = cv2.resize(mask,
                                      (original_image.shape[1], original_image.shape[0]))

                if enable_mem_opt:
                    original_image, mask, _ = optimize_image_size(
                        original_image, mask, max_img_size)
                    if i % 10 == 0:
                        gc.collect()

                traits = extract_all_wheat_traits(mask, original_image)

                if traits:
                    traits['mask_filename'] = mask_file
                    traits['original_filename'] = original_filename
                    traits['processed_time'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                    results.append(traits)
                else:
                    failed_masks.append(mask_file)

                # Save intermediate results
                if output_csv and i > 0 and (i % save_interval == 0 or i == len(mask_files) - 1):
                    temp_df = pd.DataFrame(results)
                    temp_df.set_index('mask_filename', inplace=True)
                    temp_df = temp_df.dropna(how='all').fillna(0)
                    temp_csv = f"{os.path.splitext(output_csv)[0]}_temp_{i+1}.csv"
                    temp_df.to_csv(temp_csv, na_rep='0')

            except Exception as e:
                print(f"  Error processing {mask_file}: {str(e)}")
                failed_masks.append(mask_file)
                traceback.print_exc()

        processed_count = len(results)
        if processed_count > 0:
            results_df = pd.DataFrame(results)
            results_df.set_index('mask_filename', inplace=True)
            results_df = results_df.dropna(how='all').fillna(0)

            total_time = time.time() - start_time
            print(f"\nProcessing complete!")
            print(f"Total time: {total_time / 60:.2f} min")
            print(f"Speed: {processed_count / total_time:.2f} images/sec")
            print(f"Success: {processed_count}/{len(mask_files)}")
            print(f"Failed: {len(failed_masks)}/{len(mask_files)}")

            if output_csv:
                output_dir = os.path.dirname(output_csv)
                if output_dir and not os.path.exists(output_dir):
                    os.makedirs(output_dir, exist_ok=True)
                results_df.to_csv(output_csv, na_rep='0')
                print(f"Results saved to: {output_csv}")

            return results_df
        else:
            print("Warning: No images were successfully processed")
            return None

    except KeyboardInterrupt:
        print("\nProcessing interrupted by user")
        if results and output_csv:
            results_df = pd.DataFrame(results)
            results_df.set_index('mask_filename', inplace=True)
            results_df = results_df.dropna(how='all').fillna(0)
            interrupted_csv = f"{os.path.splitext(output_csv)[0]}_interrupted.csv"
            results_df.to_csv(interrupted_csv, na_rep='0')
            print(f"Partial results saved to: {interrupted_csv}")
        return None


# =============================================================================
# Mask Quality Filtering (4-stage pipeline)
# =============================================================================

def filter_by_iqr(group, feature, threshold=1.5, remove_outliers=True):
    """IQR-based outlier detection for a single feature within a group.

    Args:
        group: DataFrame subset (typically one variety).
        feature: Column name to filter on.
        threshold: IQR multiplier for bounds.
        remove_outliers: If True, return cleaned data; if False, return outliers.

    Returns:
        Filtered DataFrame or outlier DataFrame.
    """
    if len(group) < 4:
        return group if remove_outliers else pd.DataFrame()

    Q1 = group[feature].quantile(0.25)
    Q3 = group[feature].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - threshold * IQR
    upper_bound = Q3 + threshold * IQR

    is_outlier = (group[feature] < lower_bound) | (group[feature] > upper_bound)

    if remove_outliers:
        return group[~is_outlier]
    else:
        return group[is_outlier]


def calculate_quality_score(df, weights=None):
    """Compute a composite quality score for each mask, grouped by variety.

    Features and default weights:
        convex_compactness (0.30), aspect_ratio (0.15), area_px (0.10),
        spikelet_density (0.15), spikelet_count (0.10), morans_i (0.05),
        glcm_homogeneity (0.05), glcm_correlation (0.05), glcm_contrast (-0.05)

    UK varieties receive adjusted weights: lower aspect_ratio (0.05),
    higher convex_compactness (0.40), higher spikelet_density (0.20).

    Args:
        df: DataFrame with trait columns and 'variety' column.
        weights: Optional custom weight dict.

    Returns:
        DataFrame with added 'quality_score' column.
    """
    default_weights = {
        'convex_compactness': 0.30,
        'aspect_ratio': 0.15,
        'area_px': 0.10,
        'spikelet_density': 0.15,
        'spikelet_count': 0.10,
        'morans_i': 0.05,
        'glcm_homogeneity': 0.05,
        'glcm_correlation': 0.05,
        'glcm_contrast': -0.05,
    }

    uk_weights = default_weights.copy()
    uk_weights.update({
        'aspect_ratio': 0.05,
        'convex_compactness': 0.40,
        'spikelet_density': 0.20,
    })

    weights = weights or default_weights
    result_df = df.copy()
    result_df['quality_score'] = 0

    for variety, group in result_df.groupby('variety'):
        variety_weights = uk_weights if 'UK' in variety else weights
        feature_scores = {}

        for feature, weight in variety_weights.items():
            if feature in group.columns and not group[feature].isna().all():
                min_val = group[feature].min()
                max_val = group[feature].max()
                if max_val > min_val:
                    if weight > 0:
                        feature_scores[feature] = (group[feature] - min_val) / (max_val - min_val)
                    else:
                        feature_scores[feature] = 1 - (group[feature] - min_val) / (max_val - min_val)
                else:
                    feature_scores[feature] = pd.Series(0.5, index=group.index)

                result_df.loc[group.index, 'quality_score'] += abs(weight) * feature_scores[feature]

        max_possible_score = sum(abs(w) for f, w in variety_weights.items() if f in feature_scores)
        if max_possible_score > 0:
            result_df.loc[group.index, 'quality_score'] = \
                result_df.loc[group.index, 'quality_score'] / max_possible_score

    return result_df


def filter_by_multiple_features(df, features, threshold=1.5, min_group_size=5):
    """Apply IQR filtering across multiple features simultaneously.

    Args:
        df: DataFrame with trait data.
        features: List of feature column names.
        threshold: IQR multiplier.
        min_group_size: Minimum samples per variety to apply filtering.

    Returns:
        (filtered_df, outliers_df, stats_dict)
    """
    if df is None or len(df) == 0:
        return None, None, {}

    filtered_df = df.copy()
    all_outliers = []
    stats = {'total': len(df), 'filtered': 0, 'feature_outliers': {}}

    for variety, group in df.groupby('variety'):
        if len(group) < min_group_size:
            continue

        variety_outliers_by_feature = {}

        for feature in features:
            if feature not in df.columns:
                continue
            outliers = filter_by_iqr(group, feature, threshold, remove_outliers=False)
            if len(outliers) > 0:
                variety_outliers_by_feature[feature] = set(outliers.index)
                stats['feature_outliers'][feature] = stats['feature_outliers'].get(feature, 0) + len(outliers)

        all_feature_outliers = set()
        for fo in variety_outliers_by_feature.values():
            all_feature_outliers.update(fo)

        if all_feature_outliers:
            outliers_in_variety = df.loc[list(all_feature_outliers)].copy()
            outliers_in_variety['outlier_reason'] = 'multiple_features'
            all_outliers.append(outliers_in_variety)
            filtered_df = filtered_df.drop(list(all_feature_outliers))

    outliers_df = pd.concat(all_outliers) if all_outliers else pd.DataFrame()

    stats['filtered'] = len(df) - len(filtered_df)
    stats['remaining'] = len(filtered_df)
    stats['percent_filtered'] = (stats['filtered'] / stats['total']) * 100 if stats['total'] > 0 else 0

    return filtered_df, outliers_df, stats


def filter_by_threshold(df, criteria=None):
    """Apply variety-adaptive dynamic threshold filtering.

    Uses different threshold strategies based on sample size:
      - <30 samples: very loose thresholds
      - 30-50 samples: moderate thresholds
      - UK varieties: relaxed thresholds
      - Other varieties with sufficient data: standard thresholds

    Args:
        df: DataFrame with trait data.
        criteria: Optional dict of {feature: (min_val, max_val)}.

    Returns:
        (filtered_df, outliers_df, stats_dict)
    """
    if df is None or len(df) == 0:
        return None, None, {}

    filtered_df = df.copy()
    all_outliers = []
    stats = {'total': len(df), 'filtered': 0, 'threshold_outliers': {}}

    features_to_check = {
        'convex_compactness': (0.45, None),
        'ellipse_compactness': (0.4, None),
    }

    for variety, group in df.groupby('variety'):
        total_samples = len(group)
        variety_criteria = features_to_check.copy()

        if total_samples < 30:
            area_min = max(50, group['area_px'].quantile(0.01))
            area_max = group['area_px'].quantile(0.99) * 3.0
            variety_criteria['area_px'] = (area_min, area_max)
            ar_min = max(0.05, group['aspect_ratio'].quantile(0.05))
            ar_max = group['aspect_ratio'].quantile(0.99) * 2.5
            variety_criteria['aspect_ratio'] = (ar_min, ar_max)
            if 'convex_compactness' in group.columns:
                cc_min = max(0.3, group['convex_compactness'].quantile(0.05))
                variety_criteria['convex_compactness'] = (cc_min, None)

        elif total_samples < 50:
            area_min = max(80, group['area_px'].quantile(0.05))
            area_max = group['area_px'].quantile(0.95) * 2.0
            variety_criteria['area_px'] = (area_min, area_max)
            ar_min = max(0.1, group['aspect_ratio'].quantile(0.10))
            ar_max = group['aspect_ratio'].quantile(0.98) * 2.0
            variety_criteria['aspect_ratio'] = (ar_min, ar_max)

        elif 'UK' in variety:
            ar_min = max(0.1, group['aspect_ratio'].quantile(0.20))
            ar_max = group['aspect_ratio'].quantile(0.99) * 2.0
            area_min = max(100, group['area_px'].quantile(0.05))
            area_max = group['area_px'].quantile(0.95) * 1.8
            variety_criteria['area_px'] = (area_min, area_max)
            variety_criteria['aspect_ratio'] = (ar_min, ar_max)

        else:
            ar_min = max(0.2, group['aspect_ratio'].quantile(0.40))
            ar_max = group['aspect_ratio'].quantile(0.98) * 1.8
            area_min = max(100, group['area_px'].quantile(0.05))
            area_max = group['area_px'].quantile(0.95) * 1.5
            variety_criteria['area_px'] = (area_min, area_max)
            variety_criteria['aspect_ratio'] = (ar_min, ar_max)

        variety_outliers = []
        for feature, (min_val, max_val) in variety_criteria.items():
            if feature not in group.columns:
                continue

            if min_val is not None and max_val is not None:
                outliers = group[(group[feature] < min_val) | (group[feature] > max_val)]
                cond = f"{feature} < {min_val:.2f} or > {max_val:.2f}"
            elif min_val is not None:
                outliers = group[group[feature] < min_val]
                cond = f"{feature} < {min_val:.2f}"
            elif max_val is not None:
                outliers = group[group[feature] > max_val]
                cond = f"{feature} > {max_val:.2f}"
            else:
                continue

            if len(outliers) > 0:
                stats['threshold_outliers'][feature] = stats['threshold_outliers'].get(feature, 0) + len(outliers)
                outliers_with_reason = outliers.copy()
                outliers_with_reason['outlier_reason'] = f"{feature}: {cond}"
                variety_outliers.append(outliers_with_reason)

        if variety_outliers:
            variety_all_outliers = pd.concat(variety_outliers).drop_duplicates()
            all_outliers.append(variety_all_outliers)
            filtered_df = filtered_df.drop(variety_all_outliers.index)

    outliers_df = pd.concat(all_outliers) if all_outliers else pd.DataFrame()

    stats['filtered'] = len(outliers_df)
    stats['remaining'] = len(filtered_df)
    stats['percent_filtered'] = (stats['filtered'] / stats['total']) * 100 if stats['total'] > 0 else 0

    return filtered_df, outliers_df, stats


def filter_by_quality_score(df, threshold=None, by_variety=True, min_group_size=5):
    """Filter masks by composite quality score.

    Uses variety-specific quantile thresholds when by_variety=True.
    UK varieties use a more lenient 15th percentile; others use the 25th.

    Args:
        df: DataFrame with 'quality_score' and 'variety' columns.
        threshold: Fixed threshold (overrides dynamic if provided).
        by_variety: Use per-variety dynamic thresholds.
        min_group_size: Minimum samples to apply filtering.

    Returns:
        (filtered_df, outliers_df, stats_dict)
    """
    if threshold is None and by_variety:
        thresholds = {}
        for variety, group in df.groupby('variety'):
            if len(group) < min_group_size:
                thresholds[variety] = -np.inf
            elif 'UK' in variety:
                thresholds[variety] = group['quality_score'].quantile(0.15)
            else:
                thresholds[variety] = group['quality_score'].quantile(0.25)

        threshold = df['variety'].map(thresholds)
        mask = df['quality_score'] < threshold
    else:
        threshold = threshold or 0.4
        mask = df['quality_score'] < threshold

    filtered_df = df[~mask].copy()
    outliers_df = df[mask].copy()

    if by_variety:
        outliers_df['outlier_reason'] = outliers_df.apply(
            lambda row: f"quality_score: {row['quality_score']:.3f}", axis=1)
    else:
        outliers_df['outlier_reason'] = outliers_df.apply(
            lambda row: f"quality_score: {threshold:.3f} > {row['quality_score']:.3f}", axis=1)

    stats = {
        'total': len(df),
        'filtered': len(outliers_df),
        'remaining': len(filtered_df),
        'percent_filtered': (len(outliers_df) / len(df)) * 100 if len(df) > 0 else 0
    }

    return filtered_df, outliers_df, stats


def detect_sky_background(mask, original_image=None, mask_position=None):
    """Detect whether a mask contains blue or white sky background.

    Uses BGR color statistics and optionally HSV analysis to identify
    sky-like regions. Position information (mask in upper part of image)
    is used as an additional signal.

    Args:
        mask: Mask image (BGR format for reading).
        original_image: Original image (BGR, optional).
        mask_position: (y, x, h, w) bounding box of mask in original image.

    Returns:
        True if sky background is detected.
    """
    try:
        position_score = 0
        if mask_position is not None and original_image is not None:
            y, x, h, w = mask_position
            img_height = original_image.shape[0]
            center_y_ratio = (y + h / 2) / img_height
            if center_y_ratio < 0.3:
                position_score += 0.4
            elif center_y_ratio < 0.5:
                position_score += 0.2

        if original_image is not None:
            mask_gray = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)
            _, mask_binary = cv2.threshold(mask_gray, 1, 255, cv2.THRESH_BINARY)
            if original_image.shape[:2] != mask_binary.shape:
                mask_binary = cv2.resize(mask_binary,
                                         (original_image.shape[1], original_image.shape[0]))
            mask_bool = mask_binary > 0
            roi_pixels = original_image[mask_bool]
        else:
            mask_gray = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)
            mask_bool = mask_gray > 0
            roi_pixels = mask[mask_bool]

        if len(roi_pixels) == 0:
            return False

        if len(roi_pixels) > 1000:
            indices = np.random.choice(len(roi_pixels), 1000, replace=False)
            roi_pixels = roi_pixels[indices]

        roi_bgr = roi_pixels.reshape(-1, 3).astype(np.uint8)
        bgr_mean = np.mean(roi_bgr, axis=0)
        bgr_std = np.std(roi_bgr, axis=0)

        blue_score = bgr_mean[0] - (bgr_mean[1] + bgr_mean[2]) / 2
        blue_sky_score = 0
        if (blue_score > 25 and bgr_mean[0] > 100 and
                bgr_mean[1] < 110 and bgr_mean[2] < 100 and bgr_std[0] < 50):
            blue_sky_score = 0.7
        elif (blue_score > 15 and bgr_mean[0] > 80 and
              bgr_mean[1] < 120 and bgr_mean[2] < 110 and bgr_std[0] < 60):
            blue_sky_score = 0.4

        brightness = np.mean(bgr_mean)
        color_variance = np.var(bgr_mean)
        overall_std = np.mean(bgr_std)
        white_sky_score = 0
        if brightness > 180 and color_variance < 80 and overall_std < 40:
            white_sky_score = 0.7
        elif brightness > 160 and color_variance < 120 and overall_std < 50:
            white_sky_score = 0.4

        hsv_sky_score = 0
        if blue_sky_score < 0.8 and white_sky_score < 0.8:
            temp_img = roi_bgr.reshape(1, -1, 3)
            roi_hsv = cv2.cvtColor(temp_img, cv2.COLOR_BGR2HSV).reshape(-1, 3)
            hsv_mean = np.mean(roi_hsv, axis=0)
            hsv_std = np.std(roi_hsv, axis=0)
            hue = hsv_mean[0]
            saturation = hsv_mean[1]
            value = hsv_mean[2]
            if (90 <= hue <= 140 and saturation > 50 and value > 100 and hsv_std[0] < 25):
                hsv_sky_score = 0.5

        color_score = max(blue_sky_score, white_sky_score, hsv_sky_score)
        total_score = color_score + position_score

        return total_score > 0.45

    except Exception as e:
        print(f"Sky background detection error: {str(e)}")
        return False


def enhanced_filter_flow(df, mask_dir, image_dir=None, min_group_size=5,
                         iqr_threshold=1.5, enable_color_filter=True):
    """Run the full 4-stage mask quality filtering pipeline.

    Stage 1: Sky background detection (blue/white sky regions)
    Stage 2: Dynamic threshold filtering (variety-adaptive bounds)
    Stage 3: IQR outlier filtering (convex_compactness, aspect_ratio)
    Stage 4: Quality score filtering (composite weighted score)

    Args:
        df: DataFrame with trait data and 'variety' column.
        mask_dir: Path to mask images (for sky background detection).
        image_dir: Path to original images (optional, for sky detection).
        min_group_size: Minimum variety sample count to apply filtering.
        iqr_threshold: IQR multiplier for Stage 3.
        enable_color_filter: Whether to run Stage 1 (sky detection).

    Returns:
        (filtered_df, all_outliers_df, stats_dict)
    """
    df = df.reset_index(drop=True)

    # Stage 1: Sky background
    if enable_color_filter and mask_dir:
        print("\n=== Stage 1: Sky Background Detection ===")
        filtered_1 = df.copy()
        all_outliers_1 = []
        for idx, row in df.iterrows():
            mask_path = os.path.join(mask_dir, row['mask_filename'])
            if not os.path.exists(mask_path):
                continue
            mask = cv2.imread(mask_path)
            if mask is None:
                continue
            orig_img = None
            if image_dir:
                if '_mask_' in row['mask_filename']:
                    orig_name = row['mask_filename'].split('_mask_')[0]
                else:
                    parts = row['mask_filename'].rsplit('_', 2)
                    orig_name = parts[0] if len(parts) >= 3 else row['mask_filename'].split('_')[0]
                for ext in ['.png', '.jpg', '.jpeg']:
                    p = os.path.join(image_dir, orig_name + ext)
                    if os.path.exists(p):
                        orig_img = cv2.imread(p)
                        break
            if detect_sky_background(mask, orig_img):
                outlier_row = row.copy()
                outlier_row['outlier_reason'] = 'sky_background'
                all_outliers_1.append(outlier_row)
        outliers1 = pd.DataFrame(all_outliers_1) if all_outliers_1 else pd.DataFrame()
        if not outliers1.empty:
            filtered_1 = filtered_1[~filtered_1['mask_filename'].isin(
                outliers1['mask_filename'])]
        df_stage1 = filtered_1
    else:
        df_stage1 = df.copy()
        outliers1 = pd.DataFrame()

    # Stage 2: Dynamic threshold
    print("\n=== Stage 2: Dynamic Threshold Filtering ===")
    df_stage2, outliers2, _ = filter_by_threshold(df_stage1)

    # Stage 3: IQR
    print("\n=== Stage 3: IQR Outlier Filtering ===")
    df_stage3, outliers3, _ = filter_by_multiple_features(
        df_stage2.reset_index(drop=True),
        features=['convex_compactness', 'aspect_ratio'],
        threshold=iqr_threshold,
        min_group_size=min_group_size
    )

    # Stage 4: Quality score
    print("\n=== Stage 4: Quality Score Filtering ===")
    df_with_score = calculate_quality_score(df_stage3.reset_index(drop=True))
    df_stage4, outliers4, _ = filter_by_quality_score(
        df_with_score, threshold=None, by_variety=True,
        min_group_size=min_group_size
    )

    # Merge all outliers
    outlier_frames = []
    for o in [outliers1, outliers2, outliers3, outliers4]:
        if not o.empty:
            outlier_frames.append(o.reset_index(drop=True))

    all_outliers = pd.concat(outlier_frames, ignore_index=True) if outlier_frames else pd.DataFrame()

    stats = {
        'total': len(df),
        'filtered': len(all_outliers),
        'remaining': len(df_stage4),
        'percent_filtered': (len(all_outliers) / len(df)) * 100 if len(df) > 0 else 0
    }

    return df_stage4, all_outliers, stats


# =============================================================================
# CLI Entry Point
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='Wheat Spike Trait Extraction Pipeline',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single image extraction
  %(prog)s --single-mask mask.png --single-image image.png

  # Batch extraction
  %(prog)s --mask-folder masks/ --image-folder images/ --output-csv traits.csv

  # With memory optimization
  %(prog)s --mask-folder masks/ --image-folder images/ --output-csv traits.csv --enable-memory-optimization
        """
    )

    # Single image mode
    parser.add_argument('--single-mask', type=str, default=None,
                        help='Path to a single mask image for debugging/testing')
    parser.add_argument('--single-image', type=str, default=None,
                        help='Path to the corresponding original image')

    # Batch mode
    parser.add_argument('--mask-folder', type=str, default=None,
                        help='Folder containing mask images')
    parser.add_argument('--image-folder', type=str, default=None,
                        help='Folder containing original images')
    parser.add_argument('--output-csv', type=str, default=None,
                        help='Output CSV path for batch results')

    # Processing options
    parser.add_argument('--start-index', type=int, default=0,
                        help='Start processing from this index (default: 0)')
    parser.add_argument('--sample-limit', type=int, default=None,
                        help='Maximum number of samples to process')
    parser.add_argument('--enable-memory-optimization', action='store_true',
                        help='Enable image downsampling for large images')
    parser.add_argument('--max-image-size', type=int, default=1500,
                        help='Max image dimension before downsampling (default: 1500)')
    parser.add_argument('--batch-save-interval', type=int, default=50,
                        help='Save intermediate results every N samples (default: 50)')

    # Debug options
    parser.add_argument('--feature-type', choices=['all', 'shape', 'texture', 'density'],
                        default='all', help='Show only specific feature type in debug mode')

    args = parser.parse_args()

    # Single image debug mode
    if args.single_mask and args.single_image:
        print("=== Single Image Debug Mode ===")

        mask = cv2.imread(args.single_mask, cv2.IMREAD_GRAYSCALE)
        image = cv2.imread(args.single_image)

        if mask is None or image is None:
            print("Error: Cannot read mask or image file")
            return

        if mask.shape[:2] != image.shape[:2]:
            print("Warning: Resizing mask to match image dimensions")
            mask = cv2.resize(mask, (image.shape[1], image.shape[0]))

        if args.enable_memory_optimization:
            image, mask, scale = optimize_image_size(image, mask, args.max_image_size)
            if scale < 1.0:
                print(f"Image scaled by factor {scale:.3f}")

        features = extract_all_wheat_traits(mask, image)

        print("\nExtracted features:")
        if args.feature_type != 'all':
            type_filters = {
                'shape': ['aspect', 'compact', 'area', 'perimeter'],
                'texture': ['glcm', 'lbp'],
                'density': ['spikelet', 'voronoi']
            }
            keywords = type_filters.get(args.feature_type, [])
            for k, v in features.items():
                if any(kw in k for kw in keywords):
                    print(f"  {k}: {v}")
        else:
            for k, v in features.items():
                print(f"  {k}: {v}")
        return

    # Batch mode
    if args.mask_folder and args.image_folder:
        print("=== Batch Processing Mode ===")

        if args.enable_memory_optimization:
            print(f"Memory optimization enabled (max size: {args.max_image_size}px)")

        batch_extract_all_traits(
            args.mask_folder,
            args.image_folder,
            args.output_csv,
            args.start_index,
            args.sample_limit,
            args
        )
        return

    parser.print_help()


if __name__ == "__main__":
    main()
